---
- name: Vagrant-Ansible Playbook Example
  hosts: all
  become: true

  # repodir is defined in the Vagrantfile

  # include the dnf plug in role to configure
  roles:
    - role: fedora_dnf_local_plugin
      vars:
        dlp_repodir: "{{ repo_dir }}"

  # initial task - dnf update
  tasks:
    - name: Echo repo_dir
      debug:
        msg: The dnf local repository is at {{ repo_dir }}

    - name: Refresh metadata from local repo
      shell: "dnf makecache --repo=_dnf_local"
      args:
        warn: false

    - name: DNF Update
      dnf:
        name: "*"
        state: latest
      when: dnf_update
...
