---
- hosts: all
  become: true

  # include the dnf plug in role to configure
  roles:
    - role: fedora_dnf_local_plugin
      vars:
        dlp_repodir: '/srv/repodir'

  # initial task - dnf update
  tasks:
    - name: Refresh metadata from local repo
      shell: 'dnf makecache --repo=_dnf_local'
      args:
        warn: false

    - name: DNF Update
      dnf:
        name: "*"
        state: latest
...
