# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "fedora/33-cloud-base"

  config.vm.provider :libvirt do |v|
    v.memory = 4096
  #  v.cpus = 2
  end

  # share the local repository with the vm at the same location
  config.vm.synced_folder "/srv/repodir", "/srv/repodir"

  # ansible provisioner - commented out by default
  # the ansible role is installed into a path defined by
  # ansible.cfg
#  config.vm.provision "ansible" do |ansible|
#    ansible.verbose = "v"
#    ansible.playbook = "ansible/playbook.yaml"
#    ansible.galaxy_role_file = "ansible/requirements.yaml"
#    ansible.galaxy_roles_path = "ansible/roles"
#  end
end
