---

# ansible fedora dnf plugin role
- src: https://github.com/buckaroogeek/ansible-role-fedora-dnf-local-plugin
  name: fedora_dnf_local_plugin

# ansible fedora nfs client role
- src: https://github.com/buckaroogeek/ansible-role-fedora-nfs-client
  name: fedora_nfs_client

...
